# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exp_gradient <- function(pp, Tmax, pars) {
    .Call(`_bootha_exp_gradient`, pp, Tmax, pars)
}

exp_hessian <- function(pp, Tmax, pars) {
    .Call(`_bootha_exp_hessian`, pp, Tmax, pars)
}

fib <- function(L, v, flat = FALSE) {
    .Call(`_bootha_fib`, L, v, flat)
}

exp_fib <- function(L, v, pars, pp, flat = FALSE) {
    .Call(`_bootha_exp_fib`, L, v, pars, pp, flat)
}

intensity <- function(x, pp, pars) {
    .Call(`_bootha_intensity`, x, pp, pars)
}

integrated_intensity <- function(x, pp, pars) {
    .Call(`_bootha_integrated_intensity`, x, pp, pars)
}

interpol <- function(f, x = NULL, y = NULL, flat = FALSE) {
    .Call(`_bootha_interpol`, f, x, y, flat)
}

log_lik <- function(pp, Tmax, pars, dt = 0) {
    .Call(`_bootha_log_lik`, pp, Tmax, pars, dt)
}

rib <- function(pars, v, dt = 1, flat = FALSE) {
    .Call(`_bootha_rib`, pars, v, dt, flat)
}

exp_rib <- function(pars, v) {
    .Call(`_bootha_exp_rib`, pars, v)
}

testfun <- function(x) {
    .Call(`_bootha_testfun`, x)
}

